spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/accessguard?options=-c%20TimeZone=UTC}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: validate

    show-sql: true

  flyway:
    enabled: true

server:
  port: ${PORT:8080}