name: Production Deployment

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest

    environment:
      name: production
      url: https://accessguard-7nv9.onrender.com

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Mark deployment successful
        run: echo "Deployment successful"